package id.ac.ui.cs.advprog.orderservice.model;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.List;
import java.util.UUID;

import static org.junit.jupiter.api.Assertions.*;

class OrderItemTest {

    private OrderItem orderItem;
    private UUID id;
    private UUID menuItemId;
    private Order mockOrder; // Mock the Order for context

    @BeforeEach
    void setUp() {
        id = UUID.randomUUID();
        menuItemId = UUID.randomUUID();
        mockOrder = new Order("T1"); // Or mock(Order.class)
        orderItem = new OrderItem();
        orderItem.setOrder(mockOrder); // Set the context
    }

    @Test
    void testDefaultConstructor() {
        OrderItem newItem = new OrderItem();
        assertNull(newItem.getId()); // ID should be null until generated by JPA
        assertNull(newItem.getOrder());
        assertNull(newItem.getMenuItemId());
        assertNull(newItem.getMenuItemName());
        assertEquals(0, newItem.getQuantity());
        assertEquals(0.0, newItem.getPrice());
        assertEquals(0.0, newItem.getSubtotal());
    }

    @Test
    void testParameterizedConstructorAndSubtotal() {
        OrderItem newItem = new OrderItem(mockOrder, menuItemId, "Nasi Uduk", 2, 12000.0);
        assertEquals(mockOrder, newItem.getOrder());
        assertEquals(menuItemId, newItem.getMenuItemId());
        assertEquals("Nasi Uduk", newItem.getMenuItemName());
        assertEquals(2, newItem.getQuantity());
        assertEquals(12000.0, newItem.getPrice());
        assertEquals(24000.0, newItem.getSubtotal()); // Check calculated subtotal
    }

    @Test
    void testGetSetId() {
        orderItem.setId(id);
        assertEquals(id, orderItem.getId());
    }

    @Test
    void testGetSetMenuItemId() {
        orderItem.setMenuItemId(menuItemId);
        assertEquals(menuItemId, orderItem.getMenuItemId());
    }

    @Test
    void testGetSetMenuItemName() {
        String name = "Nasi Goreng";
        orderItem.setMenuItemName(name);
        assertEquals(name, orderItem.getMenuItemName());
    }

    @Test
    void testSetQuantityUpdatesSubtotal() {
        int quantity = 2;
        orderItem.setPrice(10.0); // Set price first
        orderItem.setQuantity(quantity);
        assertEquals(quantity, orderItem.getQuantity());
        assertEquals(20.0, orderItem.getSubtotal()); // 10.0 * 2
    }

    @Test
    void testSetNegativeQuantityThrowsException() {
        assertThrows(IllegalArgumentException.class, () -> {
            orderItem.setQuantity(-1);
        });
    }

    @Test
    void testSetPriceUpdatesSubtotal() {
        double price = 15000.50;
        orderItem.setQuantity(3); // Set quantity first
        orderItem.setPrice(price);
        assertEquals(price, orderItem.getPrice());
        assertEquals(45001.50, orderItem.getSubtotal()); // 15000.50 * 3
    }

    @Test
    void testSetNegativePriceThrowsException() {
        assertThrows(IllegalArgumentException.class, () -> {
            orderItem.setPrice(-5.0);
        });
    }

    @Test
    void testGetSubtotal() {
        // Subtotal is calculated, getter should work
        orderItem.setPrice(5.0);
        orderItem.setQuantity(4);
        assertEquals(20.0, orderItem.getSubtotal());
    }

    @Test
    void testEqualsAndHashCode() {
        OrderItem item1 = new OrderItem();
        UUID generatedId = UUID.randomUUID();
        item1.setId(generatedId);

        OrderItem item2 = new OrderItem();
        item2.setId(generatedId);

        OrderItem item3 = new OrderItem();
        item3.setId(UUID.randomUUID());

        OrderItem item4 = new OrderItem(); // id is null

        assertEquals(item1, item2);
        assertNotEquals(item1, item3);
        assertNotEquals(item1, null);
        assertNotEquals(item1, new Object());
        assertEquals(item1.hashCode(), item2.hashCode()); // Hashcode relies on ID if not null
        // assertNotEquals(item1.hashCode(), item3.hashCode()); // Can clash
        assertEquals(31, item4.hashCode()); // Hashcode for null ID
    }

    @Test
    void testGetSetOrder() {
        Order anotherOrder = new Order("T99");
        orderItem.setOrder(anotherOrder);
        assertEquals(anotherOrder, orderItem.getOrder());
    }
}