package id.ac.ui.cs.advprog.orderservice.model;

import jakarta.persistence.*;
import lombok.Getter;
import lombok.Setter;

import java.util.UUID;

@Entity
@Table(name = "order_items")
@Getter
@Setter
public class OrderItem {

    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    private UUID id;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "order_id", nullable = false)
    private Order order; // Link back to the Order

    @Column(nullable = false)
    private UUID menuItemId; // ID of the item from Menu Service

    @Column(nullable = false)
    private String menuItemName;

    @Column(nullable = false)
    private int quantity;

    @Column(nullable = false)
    private double price; // Price per unit at the time of order

    @Column(nullable = false)
    private double subtotal;

    // Additional menu item properties
    @Column
    private String description;

    @Column(name = "is_cold")
    private Boolean isCold;

    @Column(name = "is_spicy")
    private Boolean isSpicy;

    @Column(name = "menu_type")
    private String menuType;

    @Column(name = "checkout_id")
    private UUID checkoutId;

    // Default constructor for JPA
    public OrderItem() {
        // ID will be generated by JPA
    }

    // Constructor for creating a new item
    public OrderItem(Order order, UUID menuItemId, String menuItemName, int quantity, double price) {
        this.order = order;
        this.menuItemId = menuItemId;
        this.menuItemName = menuItemName;
        this.price = price;
        this.setQuantity(quantity); // Use setter to calculate initial subtotal
    }

    // Enhanced constructor with additional properties
    public OrderItem(Order order, UUID menuItemId, String menuItemName, int quantity, double price, 
                     String description, Boolean isCold, Boolean isSpicy, String menuType) {
        this(order, menuItemId, menuItemName, quantity, price);
        this.description = description;
        this.isCold = isCold;
        this.isSpicy = isSpicy;
        this.menuType = menuType;
    }

    // Override setter for quantity to automatically update subtotal
    public void setQuantity(int quantity) {
        if (quantity < 0) {
            throw new IllegalArgumentException("Quantity cannot be negative");
        }
        this.quantity = quantity;
        calculateSubtotal();
    }

    // Override setter for price (less common to change after adding, but possible)
    public void setPrice(double price) {
         if (price < 0) {
            throw new IllegalArgumentException("Price cannot be negative");
        }
        this.price = price;
        calculateSubtotal();
    }

    // Method to calculate subtotal
    private void calculateSubtotal() {
        this.subtotal = this.price * this.quantity;
    }

    // Ensure Lombok generates getters and setters for other fields
    // Or implement them manually if not using Lombok for some fields.
    // We need manual setters for quantity and price for the subtotal logic.
    public UUID getId() { return id; }
    public Order getOrder() { return order; }
    public UUID getMenuItemId() { return menuItemId; }
    public String getMenuItemName() { return menuItemName; }
    public int getQuantity() { return quantity; }
    public double getPrice() { return price; }
    public double getSubtotal() { return subtotal; }

    public void setId(UUID id) { this.id = id; }
    public void setOrder(Order order) { this.order = order; }
    public void setMenuItemId(UUID menuItemId) { this.menuItemId = menuItemId; }
    public void setMenuItemName(String menuItemName) { this.menuItemName = menuItemName; }
    // Setter for subtotal is private/removed as it's calculated
    // public void setSubtotal(double subtotal) { this.subtotal = subtotal; }

    // Equals and HashCode based on ID
     @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        OrderItem orderItem = (OrderItem) o;
        return id != null && id.equals(orderItem.id);
    }

    @Override
    public int hashCode() {
        return 31; // Fixed hashCode when ID is null (before persistence)
                    // Or use getClass().hashCode() if IDs are always generated before hash is needed.
                    // If using ID after generation: Objects.hash(id);
    }
}