package id.ac.ui.cs.advprog.orderservice.model;

import com.fasterxml.jackson.annotation.JsonBackReference;
import jakarta.persistence.*;
import lombok.Getter;
import lombok.Setter;

import java.util.UUID;

@Entity
@Table(name = "order_items")
@Getter
@Setter
public class OrderItem {
    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    private UUID id;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "order_id", nullable = false)
    @JsonBackReference
    private Order order;

    @Column(nullable = false)
    private UUID menuItemId;

    @Column(nullable = false)
    private String menuItemName;

    @Column(nullable = false)
    private int quantity;

    @Column(nullable = false)
    private double price;

    @Column(nullable = false)
    private double subtotal;

    // Additional menu item properties
    @Column
    private String description;

    @Column(name = "is_cold")
    private Boolean isCold;

    @Column(name = "is_spicy")
    private Boolean isSpicy;

    @Column(name = "menu_type")
    private String menuType;

    @Column(name = "checkout_id")
    private UUID checkoutId;

    // Default constructor for JPA
    public OrderItem() {
        // ID will be generated by JPA
    }

    // Constructor for creating a new item
    public OrderItem(Order order, UUID menuItemId, String menuItemName, int quantity, double price) {
        this.order = order;
        this.menuItemId = menuItemId;
        this.menuItemName = menuItemName;
        this.price = price;
        this.setQuantity(quantity); // Use setter to calculate initial subtotal
    }

    // Builder pattern for enhanced constructor with additional properties
    public static OrderItemBuilder builder() {
        return new OrderItemBuilder();
    }
    
    public static class OrderItemBuilder {
        private Order order;
        private UUID menuItemId;
        private String menuItemName;
        private int quantity;
        private double price;
        private String description;
        private Boolean isCold;
        private Boolean isSpicy;
        private String menuType;
        
        public OrderItemBuilder order(Order order) {
            this.order = order;
            return this;
        }
        
        public OrderItemBuilder menuItemId(UUID menuItemId) {
            this.menuItemId = menuItemId;
            return this;
        }
        
        public OrderItemBuilder menuItemName(String menuItemName) {
            this.menuItemName = menuItemName;
            return this;
        }
        
        public OrderItemBuilder quantity(int quantity) {
            this.quantity = quantity;
            return this;
        }
        
        public OrderItemBuilder price(double price) {
            this.price = price;
            return this;
        }
        
        public OrderItemBuilder description(String description) {
            this.description = description;
            return this;
        }
        
        public OrderItemBuilder isCold(Boolean isCold) {
            this.isCold = isCold;
            return this;
        }
        
        public OrderItemBuilder isSpicy(Boolean isSpicy) {
            this.isSpicy = isSpicy;
            return this;
        }
        
        public OrderItemBuilder menuType(String menuType) {
            this.menuType = menuType;
            return this;
        }
        
        public OrderItem build() {
            OrderItem item = new OrderItem(order, menuItemId, menuItemName, quantity, price);
            item.description = this.description;
            item.isCold = this.isCold;
            item.isSpicy = this.isSpicy;
            item.menuType = this.menuType;
            return item;
        }
    }

    // Override setter for quantity to automatically update subtotal
    public void setQuantity(int quantity) {
        if (quantity < 0) {
            throw new IllegalArgumentException("Quantity cannot be negative");
        }
        this.quantity = quantity;
        calculateSubtotal();
    }

    // Override setter for price (less common to change after adding, but possible)
    public void setPrice(double price) {
         if (price < 0) {
            throw new IllegalArgumentException("Price cannot be negative");
        }
        this.price = price;
        calculateSubtotal();
    }

    // Method to calculate subtotal
    private void calculateSubtotal() {
        this.subtotal = this.price * this.quantity;
    }

    // Ensure Lombok generates getters and setters for other fields
    // Or implement them manually if not using Lombok for some fields.
    // We need manual setters for quantity and price for the subtotal logic.
    public UUID getId() { return id; }
    public Order getOrder() { return order; }
    public UUID getMenuItemId() { return menuItemId; }
    public String getMenuItemName() { return menuItemName; }
    public int getQuantity() { return quantity; }
    public double getPrice() { return price; }
    public double getSubtotal() { return subtotal; }

    public void setId(UUID id) { this.id = id; }
    public void setOrder(Order order) { this.order = order; }
    public void setMenuItemId(UUID menuItemId) { this.menuItemId = menuItemId; }
    public void setMenuItemName(String menuItemName) { this.menuItemName = menuItemName; }
    // Setter for subtotal is private/removed as it's calculated
    // public void setSubtotal(double subtotal) { this.subtotal = subtotal; }

    // Equals and HashCode based on ID
     @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        OrderItem orderItem = (OrderItem) o;
        return id != null && id.equals(orderItem.id);
    }

    @Override
    public int hashCode() {
        return 31; // Fixed hashCode when ID is null (before persistence)
                    // Or use getClass().hashCode() if IDs are always generated before hash is needed.
                    // If using ID after generation: Objects.hash(id);
    }
}